version: "3.7" #docker-compose的版本
services:
  node:
    image: node:12-alpine #node的镜像名
    volumes:
      - .:/var/www/html/ #node的数据卷
    ports:
      - "8081:8081" #node
    command: npm run server:start
    container_name: "re_node_1.0"

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    links:
      - "node"
    volumes:
      - .:/var/www/html/
    container_name: "re_nginx_1.0"

  mongo:
    image: mongo:4.4.1
    volumes:
      - ./db:/var/www/html/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=xy_refresh
      - MONGO_INITDB_ROOT_PASSWORD=Lxq235416..
    ports:
      - "27017:27017"
    container_name: "re_mongo_1.0"